<?php

/**
 * Core tenancy, roles, MFA, sessions and the first migration fixture.
 * Loaded by tests/integration.php (shared verify() helper).
 */
\NBE\Platform::install();
verify(DOMAIN_CURRENT_SITE === getenv('PLATFORM_DOMAIN'), 'network domain excludes development port');
$suffix = strtolower(wp_generate_password(8, false, false));
$a = wp_create_user('testa'.$suffix, wp_generate_password(40, true, true), 'a'.$suffix.'@example.invalid');
$b = wp_create_user('testb'.$suffix, wp_generate_password(40, true, true), 'b'.$suffix.'@example.invalid');
verify(!is_wp_error($a) && !is_wp_error($b), 'create independent identities');
$siteA = wpmu_create_blog('testa'.$suffix.'.'.DOMAIN_CURRENT_SITE, '/', 'Test A', $a, ['public' => 1]);
$siteB = wpmu_create_blog('testb'.$suffix.'.'.DOMAIN_CURRENT_SITE, '/', 'Test B', $b, ['public' => 1]);
verify(is_int($siteA) && is_int($siteB), 'provision subdomain tenants');
if (getenv('APP_ENV') !== 'production' && !in_array(getenv('PLATFORM_PORT'), ['80', '443'], true)) {
    verify(str_contains(get_home_url($siteA), ':'.getenv('PLATFORM_PORT')), 'tenant home URL retains development port');
}
$oldUser = get_current_user_id();
switch_to_blog($siteA);
wp_set_current_user($a);
verify(current_user_can('manage_options'), 'site A administrator');
foreach (['install_plugins','edit_plugins','upload_plugins','install_themes','manage_network','manage_network_options','unfiltered_html'] as $cap) {
    verify(!current_user_can($cap), 'tenant denied '.$cap);
}
$private = wp_insert_post(['post_title' => 'Private A','post_status' => 'private','post_author' => $a]);
$draft = wp_insert_post(['post_title' => 'Draft A','post_status' => 'draft','post_author' => $a]);
verify(current_user_can('edit_post', $draft), 'owner can edit draft');
restore_current_blog();
switch_to_blog($siteB);
verify(!current_user_can('manage_options'), 'A cannot administer B');
$bCanAdminB = false;
wp_set_current_user($b);
$bCanAdminB = current_user_can('manage_options');
verify($bCanAdminB, 'site B administrator retains own site authority');
wp_set_current_user($a);
$rest = rest_do_request(new WP_REST_Request('GET', '/nbe/v1/analytics'));
verify($rest->get_status() === 403, 'analytics endpoint denies cross-tenant access');
$network = rest_do_request(new WP_REST_Request('GET', '/nbe/v1/health'));
verify($network->get_status() === 403, 'network health denies tenant');
restore_current_blog();
switch_to_blog($siteA);
wp_set_current_user($b);
verify(!current_user_can('manage_options'), 'B cannot administer A before membership');
wp_set_current_user($a);
add_user_to_blog($siteA, $b, 'contributor');
wp_set_current_user($b);
verify(!current_user_can('publish_posts'), 'contributor cannot publish');
verify(!current_user_can('upload_files'), 'contributor cannot upload');
verify(!current_user_can('edit_post', $draft), 'contributor cannot edit another author');
add_user_to_blog($siteA, $b, 'editor');
wp_set_current_user(0);
wp_set_current_user($b);
verify(current_user_can('edit_post', $draft), 'editor can edit another author');
verify(!current_user_can('manage_options'), 'editor cannot change settings');
$author = wp_create_user('author'.$suffix, wp_generate_password(40, true, true), 'author'.$suffix.'@example.invalid');
$subscriber = wp_create_user('subscriber'.$suffix, wp_generate_password(40, true, true), 'subscriber'.$suffix.'@example.invalid');
verify(!is_wp_error($author) && !is_wp_error($subscriber), 'create role-bound identities');
add_user_to_blog($siteA, $author, 'author');
add_user_to_blog($siteA, $subscriber, 'subscriber');
wp_set_current_user($author);
verify(current_user_can('publish_posts') && current_user_can('upload_files'), 'author may publish and upload');
verify(!current_user_can('edit_post', $draft) && !current_user_can('manage_options'), 'author cannot edit another author or administer site');
wp_set_current_user($subscriber);
verify(current_user_can('read') && !current_user_can('edit_posts') && !current_user_can('upload_files'), 'subscriber can read but not publish or upload');
wp_set_current_user($a);
verify(!current_user_can('manage_network_options'), 'site administrator lacks network authority');
grant_super_admin($a);
verify(current_user_can('manage_network_options'), 'super administrator gains network authority');
revoke_super_admin($a);
verify(!current_user_can('manage_network_options'), 'revoked super administrator loses network authority');
update_site_option('nbe_readonly', true);
verify(!current_user_can('edit_post', $draft), 'emergency denies post writes');
verify(!current_user_can('upload_files'), 'emergency denies uploads');
update_site_option('nbe_readonly', false);
$bad = tempnam(sys_get_temp_dir(), 'bad');
file_put_contents($bad, '<?php echo "bad";');
$f = \NBE\Platform::upload(['tmp_name' => $bad,'name' => 'evil.php','size' => filesize($bad)]);
verify(!empty($f['error']), 'executable upload rejected');
unlink($bad);
$archive = tempnam(sys_get_temp_dir(), 'wxr');
$z = new ZipArchive();
$z->open($archive, ZipArchive::OVERWRITE);
$z->addFile(__DIR__.'/../fixtures/publication.xml', 'archive/publication.xml');
$img = tempnam(sys_get_temp_dir(), 'png');
$gd = imagecreatetruecolor(30, 20);
imagepng($gd, $img);
imagedestroy($gd);
$z->addFile($img, 'nested/blogs.dir/42/files/2020/photo one.png');
$z->close();
$crossTenantRejected = false;
try {
    \NBE\Migration::intake($archive, $siteB, $a);
} catch (RuntimeException $error) {
    $crossTenantRejected = true;
}
verify($crossTenantRejected, 'site A administrator cannot start a site B migration');
$inventoryJob = \NBE\Migration::intake($archive, $siteB, $b);
\NBE\Migration::run($inventoryJob, 20);
global $wpdb;
$inventoryRow = $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->base_prefix.'nbe_jobs WHERE id=%s', $inventoryJob));
$inventoryReport = json_decode($inventoryRow->report, true);
verify($inventoryRow->state === 'awaiting_author_mapping' && (int)$inventoryRow->cursor === 0, 'browser intake inventories before importing');
verify($inventoryReport['authors'] === ['source-alice'], 'inventory exposes imported authors for member mapping');
$job = \NBE\Migration::intake($archive, $siteA, $a, ['source-alice' => $a]);
verify(fileowner(\NBE\Migration::root().'/'.$job) === fileowner(\NBE\Migration::root()) && fileowner(\NBE\Migration::root().'/'.$job.'/original') === fileowner(\NBE\Migration::root()), 'private import is accessible to worker owner');
verify($job === \NBE\Migration::intake($archive, $siteA, $a), 'same archive returns same job');
\NBE\Migration::run($job, 2);
$row = $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->base_prefix.'nbe_jobs WHERE id=%s', $job));
verify((int)$row->cursor === 2, 'bounded batch checkpoint');
\NBE\Migration::run($job, 2);
\NBE\Migration::run($job, 2);
$row = $wpdb->get_row($wpdb->prepare('SELECT * FROM '.$wpdb->base_prefix.'nbe_jobs WHERE id=%s', $job));
$report = json_decode($row->report, true);
verify($row->state === 'needs_attention', 'missing media and unsupported type block clean completion');
verify($report['media_imported'] === 1, 'bundled media imported');
verify(isset($report['media_missing'][105]), 'missing binary reported');
verify(in_array('unsupported_type', $report['unsupported_post_types'], true), 'unknown type reported');
verify(in_array('missing/widget', $report['unsupported_blocks'], true), 'unknown block reported');
verify(in_array('unknown_widget', $report['unsupported_shortcodes'], true), 'unknown shortcode reported');
$post = get_posts(['name' => 'story-101','post_status' => 'any','numberposts' => 1])[0];
verify($post->post_author == $a, 'author mapping');
verify($post->post_date === '2020-05-06 10:20:30', 'publication date preserved');
verify($post->post_modified === '2021-01-02 11:00:00', 'modified date preserved');
verify(!str_contains($post->post_content, '<script>'), 'imported scripts stripped');
verify(!str_contains($post->post_content, 'source.example'), 'old content URLs replaced');
verify(!str_contains($post->post_content, '/files/'), 'legacy files URLs replaced');
verify(get_post_meta($post->ID, 'oauth_token', true) === '', 'credential metadata excluded');
verify(get_post_meta($post->ID, 'public_credit', true) === 'Archive collective', 'safe custom metadata');
verify(is_file(get_attached_file(get_post_thumbnail_id($post->ID))), 'featured image binary exists');
verify(parse_url(wp_get_attachment_url(get_post_thumbnail_id($post->ID)), PHP_URL_HOST) === parse_url(home_url('/'), PHP_URL_HOST), 'featured image URL stays on the destination tenant');
$comments = get_comments(['post_id' => $post->ID,'orderby' => 'comment_ID','order' => 'ASC']);
verify(count($comments) === 2, 'comments preserved');
verify($comments[1]->comment_parent == $comments[0]->comment_ID, 'comment hierarchy');
verify($comments[0]->comment_author_IP === '', 'comment IP omitted');
$before = (int)$wpdb->get_var("SELECT COUNT(*) FROM $wpdb->posts");
$wpdb->update($wpdb->base_prefix.'nbe_jobs', ['cursor' => 0,'state' => 'queued'], ['id' => $job]);
\NBE\Migration::run($job, 20);
verify((int)$wpdb->get_var("SELECT COUNT(*) FROM $wpdb->posts") === $before, 'retry creates no duplicate posts');
verify(class_exists('Two_Factor_Core'), 'MFA core loaded');
$totp = Two_Factor_Totp::get_instance();
$key = Two_Factor_Totp::generate_key();
$totp->set_user_totp_key($a, $key);
$code = Two_Factor_Totp::calc_totp($key);
verify(Two_Factor_Totp::is_valid_authcode($key, $code), 'valid TOTP');
verify(!Two_Factor_Totp::is_valid_authcode($key, '00000000'), 'invalid TOTP denied');
verify($totp->validate_code_for_user(get_userdata($a), $code), 'TOTP login validation');
verify(!$totp->validate_code_for_user(get_userdata($a), $code), 'TOTP replay denied');
$providers = Two_Factor_Core::get_providers();
verify((bool)array_filter(array_keys($providers), fn ($name) => str_contains(strtolower($name), 'webauthn')), 'WebAuthn provider registered');
verify(!isset($providers['Two_Factor_Email']), 'email not offered as MFA');
$session = WP_Session_Tokens::get_instance($a);
$token = $session->create(time() + 3600);
verify($session->verify($token), 'session valid');
$session->destroy_all();
verify(!$session->verify($token), 'session revocation');
unlink($archive);
unlink($img);
restore_current_blog();
wp_set_current_user($oldUser);
